/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp_6_ejercicio2;

/**
 *
 * @author Lenovo
 */
public class ListadoPorPrecio extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListadoPorPrecio
     */
    public ListadoPorPrecio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLEntre$ = new javax.swing.JLabel();
        jTConsultaPrecio1 = new javax.swing.JTextField();
        jLLabelY = new javax.swing.JLabel();
        jTConsultaPrecio2 = new javax.swing.JTextField();
        jLTituloListadoPrecio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTablaDePrecios = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLEntre$.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEntre$.setText("Entre $");

        jTConsultaPrecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTConsultaPrecio1ActionPerformed(evt);
            }
        });

        jLLabelY.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLLabelY.setText("y");

        jTConsultaPrecio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTConsultaPrecio2ActionPerformed(evt);
            }
        });

        jLTituloListadoPrecio.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLTituloListadoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloListadoPrecio.setText("Listado por Precio");

        jTTablaDePrecios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTTablaDePrecios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLEntre$, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jTConsultaPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLLabelY, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jTConsultaPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTituloListadoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLTituloListadoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTConsultaPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLLabelY)
                    .addComponent(jLEntre$)
                    .addComponent(jTConsultaPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTConsultaPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTConsultaPrecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTConsultaPrecio1ActionPerformed

    private void jTConsultaPrecio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTConsultaPrecio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTConsultaPrecio2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLEntre$;
    private javax.swing.JLabel jLLabelY;
    private javax.swing.JLabel jLTituloListadoPrecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTConsultaPrecio1;
    private javax.swing.JTextField jTConsultaPrecio2;
    private javax.swing.JTable jTTablaDePrecios;
    // End of variables declaration//GEN-END:variables
}
